### PR TITLE
Formatting / thread support / auto history sync

### PR DESCRIPTION
**Pull request by nicois**
Alex has done some good work on formatting.

I have built on that, supporting slack threads, as well as using channel.history to sync any messages sent while the service wasn't running. It also obsoletes the need to import from a manual slack backup - and the import wasn't working for me anyway.

There are a few other small changes too, like fixing the CRLF endings, the the main changes are listed above.

### CODE REVIEW

**Comment by docmarionum1** [comment]
@nicois As far as I can tell, the `channels.history` API call has the same 10,000 message limitation that search normally has, so you won't be able to sync further back than that if you've never set up the archivebot DB before.  What was breaking for you with the manual import? We need to ensure the bulk import is still an option for the initial setup.  

Besides that, the changes look good.

**Comment by stalltron** [comment]
Hi, when do you anticipate merging this PR? We'd love the ability to archive private channels, and the other changes are welcome also. Thanks!

**Comment by docmarionum1** [comment]
@stalltron I was hoping to get a resolution to the the problem with manual import that @nicois mentioned before getting rid of the import process.  As I said, using the API for the initial import didn't work for me past 10k most recent messages.  

If you'd like to send me a PR with specifically the features you were looking for (private channels, etc.) I'd be happy to take a look and merge it.  Otherwise I'll have to make some time to go through this in more detail maybe later this week.

**Comment by stalltron** [comment]
@docmarionum1 Ok, understood. Will look into submitting a PR - right now archiving private channels and having the ability to query messages from those channels is most important. 

Before we do that, do you (realistically) anticipate getting to this current PR in the foreseeable future?

**Comment by docmarionum1** [comment]
@stalltron See https://github.com/docmarionum1/slack-archive-bot/commit/e4331a329f4e0b7419cbf0b004e8941126bb6d3a

Let me know if that does what you're looking for.

**Comment by stalltron** [comment]
@docmarionum1 Looks like it! Can search the private groups now but I'm not sure if the most recent data is being archived? Will continue to test it. Thanks for the work!

**Comment by DenisIzmaylov** [comment]
how is going on? :)

**Pull request closed without merging**
