### PR TITLE
Make search results prettier by updating format, adding blank line, etc.

### PR DESCRIPTION
**Pull request by jaybeaton**
I've tweaked the formatting of the search results to make them a little prettier.  This uses at link for the user,  formats the date nicely, and adds some spacing in between each result.  See screenshot:

Screenshot 2019-07-23 16 55 54

A bunch of whitespace got changed, but the only real change is around line 209.

### CODE REVIEW

**Comment by docmarionum1** [comment]
Thanks @jaybeaton and @seanbeaton!  It looks good. 

It'll have to wait till I get back from vacation in August to test and merge.

**Comment by l3oxy** [comment]
I love it!

**Comment by denis-trofimov** [comment]
@docmarionum1 hi! please come back
@jaybeaton why so much "whitespaces" change? I would recommend to do another merge for code style corrections only.

**Comment by docmarionum1** [comment]
Sorry, I completely lost track of this! This is great. Thanks!

**Pull request merged**
